server:
    port: 3002

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/harvester
        username: root
        password: root
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true

    jpa:
        database: POSTGRESQL
        show_sql: false
        hibernate:
            ddl-auto: create-drop
            naming:
              physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false

management:
  port: 3001
